import { jmap } from '../../utils.ts';

export type RenderDnsmasqConfProps = {
    port: number;
    dns: string[];
    addressGroups: {
        group: string;
        addresses: {
            domain: string;
            ip: string;
        }[];
    }[];
};

export const renderDnsmasqConf = ({ port, dns, addressGroups }: RenderDnsmasqConfProps) => /* conf */`
# File generated by net-config-gen

port=${port}
bind-interfaces

# DNS servers
${jmap(dns.map(ip => /* conf */`
server=${ip}
`))}

${jmap(addressGroups.map(({ group, addresses }) => /* conf */`

# ${group}

${jmap(addresses.map(({ domain, ip }) => /* conf */`
address=/${domain}/${ip}
`))}

`))}

# cache
cache-size=1000

# --debug--
# log-queries
# log-dhcp
`;
