import { rif } from '../../utils.ts';

export type RenderCaddyfileProps = {
    email: string;
    restrictedSnippets: RenderRestrictedSnippet[];
    addresses: RenderAddress[];
};

export type RenderRestrictedSnippet = {
    name: string;
    ipSubnets: string[];
};

export type RenderAddress = {
    domain: string;
    snippetName?: string;
    paths: {
        path: string;
        ip: string;
        port: number;
        ssl: boolean;
    }[];
};

export const renderCaddyfile = ({ email, restrictedSnippets, addresses }: RenderCaddyfileProps) => /* sh */`
# File generated by net-config-gen

{
    email ${email}

    # debug
}

# Snippets

${restrictedSnippets.map(({ name, ipSubnets }) => /* sh */`

(${name}) {
    @external not remote_ip ${ipSubnets.join(" ")}

    handle @external {
        respond "Forbidden (client_ip: {client_ip})" 403
    }
}

`).join("")}

# Addresses

${addresses.map(({ domain, snippetName, paths }) => `

${domain} {

${rif(snippetName, `
    import ${snippetName}
`)}

${paths
        .sort((p1, p2) => p2.path.length - p1.path.length)
        .map(({ path, ip, port, ssl }) => `
        
            ${rif(path, `
                handle ${path} {
            `)}
                
                reverse_proxy ${rif(ssl, "https://")}${ip}:${port}${rif(ssl, ` {
                    transport http {
                        tls_insecure_skip_verify
                    }
                }`)}
                
            ${rif(path, `
                }
            `)}
        `).join('')}
}

`).join('')}

# Default case

:80, :443 {
	respond "Not found (client_ip: {client_ip})" 404
}

`;