import yaml from 'yaml';
import z from 'zod';
import type { MainSchema, ServiceSchema } from '../../schema.ts';

export const genHomepageSchema = z.object({
    type: z.literal('homepage'),
    safeMode: z.boolean().optional(),
    paths: z.object({
        "services.yaml": z.string().nonempty(),
    }),
});
export type GenHomepageOptions = z.infer<typeof genHomepageSchema>;

type HPService = {
    icon?: string;
    href?: string;
    description?: string;
    ping?: string;
    siteMonitor?: string;
    widget?: unknown;
};

type HPServices = {
    [ name: string ]: HPService | HPServices;
}[];

export const genHomepage = async (generatorService: ServiceSchema, networks: MainSchema[ 'networks' ], options: GenHomepageOptions) => {
    const services: HPServices = [];

    const sortServices = (services: HPServices) => {
        if (!options.safeMode) {
            return;
        }

        services.sort((a, b) => {
            const aValue = Object.values(a)[ 0 ];
            const bValue = Object.values(b)[ 0 ];

            if (Array.isArray(aValue) || Array.isArray(bValue)) {
                return 0;
            }

            return aValue.href && !bValue.href ? -1 : 0;
        });
    };

    networks.forEach(network => {
        const networkGroup: HPServices = [];

        network.peers.forEach(peer => {
            const peerGroup: HPServices = [];

            const checkService = (service: ServiceSchema) => {
                (service.access ?? [])
                    .filter(access => access.type === 'http')
                    .toSorted((a, _) => a.domain ? -1 : 1)
                    .forEach(access => {
                        if (peerGroup.flatMap(Object.keys).includes(service.name)) {
                            return;
                        }

                        const displayHref = service.role !== 'reverse-proxy' && (!options.safeMode || (access.expose_outside_vpn && peer.type !== 'router'));

                        if (access.domain) {
                            const href = access.domain.includes('://')
                                ? access.domain
                                : [
                                    access.ssl ? 'https' : 'http',
                                    access.domain
                                ].join('://');

                            peerGroup.push({
                                [ service.name ]: {
                                    icon: service.icon,
                                    href: displayHref ? href : undefined,
                                    description: service.description,
                                    siteMonitor: href,
                                },
                            });
                        } else {
                            const ip = service.vpn_ip ?? service.lan_ip;
                            if (!ip) {
                                return;
                            }

                            const ping = [
                                access.ssl ? 'https' : 'http',
                                ip
                            ].join('://');

                            const href = access.port
                                ? ping + ':' + access.port
                                : ping;

                            peerGroup.push({
                                [ service.name ]: {
                                    icon: service.icon,
                                    href: displayHref ? href : undefined,
                                    description: service.description,
                                    ping,
                                },
                            });
                        }
                    });

                service.services?.forEach(s => checkService({
                    lan_ip: service.lan_ip,
                    vpn_ip: service.vpn_ip,
                    domain: service.domain,
                    ...s,
                }));
            };

            peer.services?.forEach(service => checkService({
                lan_ip: peer.lan_ip,
                vpn_ip: peer.vpn_ip,
                domain: peer.domain,
                ...service,
            }));

            sortServices(peerGroup);

            if (peerGroup.length > 0) {
                networkGroup.push({ [ peer.name ]: peerGroup });
            }
        });

        if (networkGroup.length > 0) {
            services.push({ [ network.name ]: networkGroup });
        }
    });

    return {
        type: options.type,
        files: {
            [ options.paths[ 'services.yaml' ] ]: '# File generated by net-config-gen\n'
                + '# https://gethomepage.dev/configs/services\n'
                + yaml.stringify(services),
        },
    };
};
